### ISSUE TITLE
Update to YAKS 0.1.0

### ISSUE THREAD

**Issue by christophd** [openshift-integration/camel-k-example-event-streaming#43]
Tests need an update once YAKS 0.1.0 is released. Kafka steps have slightly changed in wording to align with steps other modules. This way steps of different modules can be combined in a single test and the user can make use of the very same concepts for specifying message body and header content.

prior to 0.1.0
```gherkin
send message to Kafka with body
(?:expect|verify) message in Kafka with body
```

0.1.0
```gherkin
send (?:K|k)afka message with body
(?:expect|verify) (?:K|k)afka message with body
```

**Comment by christophd** [comment]
0.1.0 has not been released yet. I'll keep you posted once it is available

**Comment by apupier** [comment]
yaks 0.4.0 has been released https://github.com/citrusframework/yaks/tree/v0.4.0

@christophd I guess this example needs to be updated then? Maybe other modifications?
