### ISSUE TITLE
Jitpack dependency in quickstart refers to main-SNAPSHOT in 1.6.x branch 

### ISSUE THREAD

**Issue by lfabriko** [openshift-integration/camel-k-example-event-streaming#71]
Fix https://github.com/openshift-integration/camel-k-example-event-streaming/commit/5b2ee28c3183fb76235c7fa3db420b1424085156 sets branch to `main-SNAPSHOT` although it is on `1.6.x` branch.

@squakez

**Comment by christophd** [comment]
Should be fixed
